# Create test images directory
mkdir -p test_images
mkdir -p input
mkdir -p output

echo "Face Enhancer project structure created successfully!"
echo ""
echo "Project structure:"
echo "├── CMakeLists.txt          # Build configuration"
echo "├── README.md               # Comprehensive documentation"
echo "├── config.txt              # Configuration file"
echo "├── build.bat               # Windows build script"
echo "├── build.sh                # Linux/macOS build script"
echo "├── test_enhancer.py        # Test script"
echo "├── src/"
echo "│   ├── main.cpp            # Application entry point"
echo "│   ├── face_enhancer.cpp   # Core enhancement logic"
echo "│   ├── image_processor.cpp # Image I/O and utilities"
echo "│   ├── enhancement_algorithms.cpp # Processing algorithms"
echo "│   ├── face_detector.cpp   # Face detection methods"
echo "│   ├── utils.cpp           # Utility functions"
echo "│   └── include/"
echo "│       ├── face_enhancer.h"
echo "│       ├── image_processor.h"
echo "│       ├── enhancement_algorithms.h"
echo "│       ├── face_detector.h"
echo "│       └── utils.h"
echo "├── test_images/            # Place test images here"
echo "├── input/                  # Default input directory"
echo "└── output/                 # Default output directory"
echo ""
echo "To build and run:"
echo "1. Install OpenCV 4.x"
echo "2. Run build.bat (Windows) or ./build.sh (Linux/macOS)"
echo "3. Place test images in test_images/ directory"
echo "4. Run: ./face_enhancer -i test_images/image.jpg -o output/enhanced.jpg"
echo ""
echo "For batch processing:"
echo "   ./face_enhancer -i test_images -o output --batch"
echo ""
echo "For help:"
echo "   ./face_enhancer --help"